### ISSUE TITLE
Setting up for local storage

### ISSUE THREAD

**Issue by absim29** [NoroffFEU/ai-project#10]
Basic local storage JS functions:

- add to local storage
- get from local storage 
- remove from local storage

**Comment by Teitrheim** [comment]
Maybe have som descriptions next time? I cant see whats done, only the headline.

**Comment by Teitrheim** [comment]
Since this is code I will wait for Oliver to answer me since maybe QA should review this. I asked him what I should review and what QA should review, but he has not answered yet. I belive all code should go through QA, but i am not sure...
