### ISSUE TITLE
Register and Login with Noroff API (v2) JS

### ISSUE THREAD

**Issue by Teitrheim** [NoroffFEU/ai-project#15]
Creating login function.

- [x] Research how to write the code

- [x] Research if we need API-key

- [x] Create the code

**Comment by lordaake** [comment]
Will you use the Noroff API?

**Comment by absim29** [comment]
Yes, I was planning to use the Noroff API, not sure if that will work?

**Comment by Ulvounth** [comment]
Code created, waiting for review.
