### ISSUE TITLE
Create a functional mid-fi wireframe DESKTOP prototype for testing

### ISSUE THREAD

**Issue by Frederik-Rustad** [NoroffFEU/ai-project#23]

**Comment by Frederik-Rustad** [comment]
ready for testing

**Comment by CharlotteValset** [comment]
Suggestions and things to consider is made as comments in wireframes

**Comment by EF-Pami** [comment]
Hi, at the About App page, under the menu bar the "Your Week" is not clickable like the other menu elements. Is there maybe a particular reason for that or just a slide mistake surely?

**Comment by Frederik-Rustad** [comment]
the menu element "Your Week" now works from "About App" page and "How to use" Page
