### ISSUE TITLE
Create user testing goals and tasks

### ISSUE THREAD

**Issue by Frederik-Rustad** [NoroffFEU/ai-project#34]

**Comment by Frederik-Rustad** [comment]
User test tasks


Task 1
Add a new task (title)
Add a new task to task board as a “not logged in”-user (description)


Task 2
Sign up and log in into the app.
Locate the sign up page, sign up and log in to the app.


Task 3
Find a task that you need more help to complete
Find a task that you need more help to complete and start a chat with the AI-bot


 Task 4
Navigate to the weekly calendar list
Locate to the page where you can view your tasks in a weekly calendar

Task 5
Find a task and delete it
Find a task that you want to remove from your task list and delete it

**Comment by CharlotteValset** [comment]
Great job!
