### ISSUE TITLE
Go through feedback from MOBILE user test and make improvements where needed

### ISSUE THREAD

**Issue by Zaracki** [NoroffFEU/ai-project#59]

**Comment by Zaracki** [comment]
Regarding design feedback, numerous users encountered difficulties with tasks 3 and 5, specifically in interacting with the AI and deleting tasks. Should change the way to open individual tasks? The current "Assist" button may not clearly indicate its function to open a single task.

**Comment by Zaracki** [comment]
Changes have been made now to solve some of the issues our testers faced and brought to our attention.

**Comment by CharlotteValset** [comment]
Great!
