### ISSUE TITLE
Go through feedback from DESKTOP user test and make improvements where needed

### ISSUE THREAD

**Issue by Frederik-Rustad** [NoroffFEU/ai-project#72]

**Comment by Frederik-Rustad** [comment]
based on the feedback I need to find an agreement with mobile for:

- easier access to "your Week" on mobile and desktop,
- change Task list pages for ease to delete and edit a task, (MAKE LESS CLUTTERED)

**Comment by Frederik-Rustad** [comment]
We have agreed on changes and are doing the final touches, to be ready to make a UseBerry test to address the changes.

**Comment by CharlotteValset** [comment]
Great!
